// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-inventory.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.89.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-inventory.ts
var list_inventory_default = defineTool({
  name: "list_inventory",
  title: "List inventory items",
  description: "List the signed-in user's inventory items, optionally filtered by a name/SKU search term, category or location.",
  inputSchema: {
    search: z.string().optional().describe("Text to match against item name or SKU."),
    category: z.string().optional().describe("Filter by category."),
    location: z.string().optional().describe("Filter by storage location."),
    limit: z.number().int().min(1).max(200).optional().describe("Maximum rows to return (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, category, location, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("inventory_items").select("id,name,sku,category,quantity,unit,unit_price,reorder_level,location,expiry_date").order("name").limit(limit ?? 50);
    if (search) query = query.or(`name.ilike.%${search}%,sku.ilike.%${search}%`);
    if (category) query = query.eq("category", category);
    if (location) query = query.eq("location", location);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { items: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/low-stock-report.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var low_stock_report_default = defineTool2({
  name: "low_stock_report",
  title: "Low stock report",
  description: "List inventory items whose quantity is at or below their reorder level, so restocking can be planned.",
  inputSchema: {
    limit: z2.number().int().min(1).max(200).optional().describe("Maximum rows to return (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("inventory_items").select("id,name,sku,quantity,unit,reorder_level,location,supplier_id").order("quantity").limit(500);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const low = (data ?? []).filter((item) => item.reorder_level != null && item.quantity <= item.reorder_level).slice(0, limit ?? 50);
    return {
      content: [{ type: "text", text: JSON.stringify(low, null, 2) }],
      structuredContent: { items: low, count: low.length }
    };
  }
});

// src/lib/mcp/tools/expiring-items.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var expiring_items_default = defineTool3({
  name: "expiring_items",
  title: "Expiring items",
  description: "List perishable inventory items expiring within a number of days (including already-expired items).",
  inputSchema: {
    days: z3.number().int().min(0).max(365).optional().describe("Days ahead to look (default 30).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ days }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const horizonDays = days ?? 30;
    const cutoff = new Date(Date.now() + horizonDays * 864e5).toISOString().slice(0, 10);
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("inventory_items").select("id,name,sku,quantity,unit,location,expiry_date").not("expiry_date", "is", null).lte("expiry_date", cutoff).order("expiry_date").limit(200);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { items: data ?? [], cutoff, days: horizonDays }
    };
  }
});

// src/lib/mcp/tools/record-stock-movement.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^3.25.76";
var record_stock_movement_default = defineTool4({
  name: "record_stock_movement",
  title: "Record stock movement",
  description: "Record an incoming or outgoing stock movement for an inventory item and update its quantity accordingly.",
  inputSchema: {
    inventory_item_id: z4.string().uuid().describe("ID of the inventory item (from list_inventory)."),
    movement_type: z4.enum(["incoming", "outgoing"]).describe("Direction of the movement."),
    quantity: z4.number().positive().describe("Quantity moved (positive number)."),
    notes: z4.string().optional().describe("Optional note about this movement."),
    from_location: z4.string().optional(),
    to_location: z4.string().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const userId = ctx.getUserId();
    const supabase = supabaseForUser(ctx);
    const { data: item, error: itemError } = await supabase.from("inventory_items").select("id,name,quantity").eq("id", input.inventory_item_id).maybeSingle();
    if (itemError) return { content: [{ type: "text", text: itemError.message }], isError: true };
    if (!item) return { content: [{ type: "text", text: "Inventory item not found." }], isError: true };
    const delta = input.movement_type === "incoming" ? input.quantity : -input.quantity;
    const newQuantity = Math.max(0, Number(item.quantity) + delta);
    const { error: moveError } = await supabase.from("stock_movements").insert({
      inventory_item_id: input.inventory_item_id,
      movement_type: input.movement_type,
      quantity: input.quantity,
      notes: input.notes ?? null,
      from_location: input.from_location ?? null,
      to_location: input.to_location ?? null,
      user_id: userId,
      created_by: userId
    });
    if (moveError) return { content: [{ type: "text", text: moveError.message }], isError: true };
    const { error: updateError } = await supabase.from("inventory_items").update({ quantity: newQuantity }).eq("id", input.inventory_item_id);
    if (updateError) return { content: [{ type: "text", text: updateError.message }], isError: true };
    const summary = `${input.movement_type} ${input.quantity} of "${item.name}". Stock ${item.quantity} \u2192 ${newQuantity}.`;
    return {
      content: [{ type: "text", text: summary }],
      structuredContent: {
        item_id: item.id,
        name: item.name,
        previous_quantity: item.quantity,
        new_quantity: newQuantity
      }
    };
  }
});

// src/lib/mcp/tools/list-suppliers.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z5 } from "npm:zod@^3.25.76";
var list_suppliers_default = defineTool5({
  name: "list_suppliers",
  title: "List suppliers",
  description: "List the signed-in user's suppliers with contact details, optionally filtered by name.",
  inputSchema: {
    search: z5.string().optional().describe("Text to match against supplier name."),
    limit: z5.number().int().min(1).max(200).optional().describe("Maximum rows to return (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("suppliers").select("id,name,contact_person,email,phone,address").order("name").limit(limit ?? 50);
    if (search) query = query.ilike("name", `%${search}%`);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { suppliers: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "gelczbmbttziuaawwkxb";
var mcp_default = defineMcp({
  name: "optimal-stock-pro",
  title: "Optimal Stock Pro",
  version: "0.1.0",
  instructions: "Inventory tools for Optimal Stock Pro. Use `list_inventory` to find items, `low_stock_report` for restocking, `expiring_items` for perishables nearing expiry, `list_suppliers` for supplier contacts, and `record_stock_movement` to log incoming or outgoing stock (this updates item quantities).",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_inventory_default,
    low_stock_report_default,
    expiring_items_default,
    record_stock_movement_default,
    list_suppliers_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
